### ISSUE TITLE
Realidad Aumentada. realidad mixta. realidad virtual

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Valentiin01#1]
[Infografía Realidad Aumentada Genaro Santiago Valentín.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Valentiin01/files/14310409/Infografia.Realidad.Aumentada.Genaro.Santiago.Valentin.pdf)

**Comment by NoeliaGlez** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
